<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNBEFSp5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNBEFSp5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNBEFSp5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNBEFSp5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNBEFSp5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NBEFSp5',
    'container.build_id' => 'b15e78b5',
    'container.build_time' => 1572524292,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNBEFSp5');
